[workspace]
members = [
    "participant",
    "trusted-dealer",
    "dkg",
    "coordinator",
    "tests",
    "server",
]
default-members = [
    "participant",
    "trusted-dealer",
    "dkg",
    "coordinator",
    "tests",
    "server"
]
resolver = "2"
