[package]
name = "participant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
frost-ed25519 = { version = "1.0.0", features = ["serde"] }
reddsa = { git = "https://github.com/ZcashFoundation/reddsa.git", rev = "81c649c412e5b6ba56d491d2857f91fbd28adbc7", features = ["frost"] }
hex = "0.4"
rand = "0.8"
eyre = "0.6.12"
exitcode = "1.1.2"
serde_json = "1.0"
clap = { version = "4.5.6", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
message-io = "0.18"
reqwest = { version = "0.11.23", features = ["json"] }
server = { path = "../server" }

[features]
redpallas = []
default = []
