[package]
name = "participant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frost-ed25519 = "0.5.0"
hex = "0.4"
rand = "0.8"
exitcode = "1.1.2"
