[package]
name = "participant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frost-ed25519 = { path = "../../frost/frost-ed25519/" }
hex = "0.4"
