name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_ed25519:
    name: Test with ed25519
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  test_redpallas:
    name: Test with redpallas
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features redpallas

  test_ed25519_sockets:
    name: Test with ed25519 and sockets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-05
      - run: cargo test --features sockets

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt, clippy
          toolchain: nightly-2024-02-05
      - name: Run clippy manually without annotations
        run: cargo clippy --all-targets -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
          toolchain: nightly-2024-02-05
      - uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: cargo fmt --all -- --check

  actionlint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: reviewdog/action-actionlint@v1.41.0
        with:
          level: warning
          fail_on_error: false
